version: '3.8'

services:
  # Production service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: company-app
    networks:
      - app-network

  # Development service with hot reload
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3750:3750"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    container_name: company-app-dev
    networks:
      - app-network
    profiles:
      - dev

  # Service to run npm commands without installing Node.js on host
  npm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    container_name: company-npm
    networks:
      - app-network
    profiles:
      - tools
    command: tail -f /dev/null  # Keep container running

networks:
  app-network:
    driver: bridge

