version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: company-app
    networks:
      - app-network

  # Development service (optional - for development with hot reload)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3750:3750"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    container_name: company-app-dev
    networks:
      - app-network
    profiles:
      - dev

networks:
  app-network:
    driver: bridge

